/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment.vue')['default']
    Comments: typeof import('./src/components/comments.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    MiniPlayer: typeof import('./src/components/mini-player.vue')['default']
    MvCard: typeof import('./src/components/mv-card.vue')['default']
    Player: typeof import('./src/components/player.vue')['default']
    Playlist: typeof import('./src/components/playlist.vue')['default']
    PlaylistCard: typeof import('./src/components/playlist-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesHistory: typeof import('./src/components/routes-history.vue')['default']
    Search: typeof import('./src/components/search.vue')['default']
    SongCard: typeof import('./src/components/song-card.vue')['default']
    SongTable: typeof import('./src/components/song-table.vue')['default']
    Theme: typeof import('./src/components/theme.vue')['default']
    TopPlaylistCard: typeof import('./src/components/top-playlist-card.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
    VituralList: typeof import('./src/components/vitural-list.vue')['default']
    WithPagination: typeof import('./src/components/with-pagination.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
